INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(1, 1, 4079, 'alaing@defensoria.ms.gov.br', 'Administrador', '');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(2, 2, 4079, 'edilce@defensoria.ms.gov.br', 'Edilce Pahins Duarte', '19');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(3, 3, 4079, 'marcelosalles@defensoria.ms.gov.br', 'Marcelo Moraes Salles', '02');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(4, 4, 4079, 'claudiav.assessoria@defensoria.ms.gov.br', 'Claudia Valderis Carpejani do Amaral', '02');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(5, 5, 4079, 'guilhermec@defensoria.ms.gov.br', 'Guilherme Cambraia de Oliveira', '04');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(6, 6, 4079, 'stebbina.assessoria@defensoria.ms.gov.br', 'Stebbin Athaides Roberto da Silva', '04');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(7, 7, 4079, 'mamelia@defensoria.ms.gov.br', 'Maria Amélia de Araujo Sant''Ana', '05');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(8, 8, 4079, 'tiagof.assessoria@defensoria.ms.gov.br', 'Tiago Ferreira dos Santos', '05');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(9, 9, 4079, 'zelianasabala@defensoria.ms.gov.br', 'Zeliana Luzia Delarissa Sabala', '06');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(10, 10, 4079, 'felipea.assessoria@defensoria.ms.gov.br', 'Felipe Alves Rodrigues', '06');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(11, 11, 4079, 'florisvaldos@defensoria.ms.gov.br', 'Florisvaldo Souza Cayres', '07');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(12, 12, 4079, 'cristianep.assessoria@defensoria.ms.gov.br', 'Cristiane Pereira da Silva', '07');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(13, 13, 4079, 'ajoao@defensoria.ms.gov.br', 'Antonio João de Andrade', '08');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(14, 14, 4079, 'janainac.assessoria@defensoria.ms.gov.br', 'Janaina Cornachini Ferreira', '08');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(15, 15, 4079, 'renator@defensoria.ms.gov.br', 'Renato Rodrigues dos Santos', '09');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(16, 16, 4079, 'anas.assessoria@defensoria.ms.gov.br', 'Ana Paula da Silva Zuque', '09');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(17, 17, 4079, 'pdinis@defensoria.ms.gov.br', 'Paulo Dinis Martins Brum', '10');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(18, 18, 4079, 'rodrigof.assessoria@defensoria.ms.gov.br', 'Rodrigo de Farias Rueda', '10');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(19, 19, 4079, 'heltonc@defensoria.ms.gov.br', 'Helton Campos da Costa', '11');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(20, 20, 4079, 'joaop.assessoria@defensoria.ms.gov.br', 'João Paulo da Silva Antunes', '11');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(21, 21, 4079, 'iltonb@defensoria.ms.gov.br', 'Ilton Barreto da Motta', '13');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(22, 22, 4079, 'marielens.assessoria@defensoria.ms.gov.br', 'Marielen Segatto de Faria', '13');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(23, 23, 4079, 'elianae@defensoria.ms.gov.br', 'Eliana Etsumi Tsunoda', '15');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(24, 24, 4079, 'thaisp.assessoria@defensoria.ms.gov.br', 'Thais Paes de Campos', '15');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(25, 25, 4079, 'fabior@defensoria.ms.gov.br', 'Fábio Rógerio Rombi da Silva', '16');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(26, 26, 4079, 'katherinej.assessoria@defensoria.ms.gov.br', 'Katherine Johanna Lang Oliveira', '16');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(27, 27, 4079, 'gloriaf@defensoria.ms.gov.br', 'Glória de Fátima F. Galbiati', '17');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(28, 28, 4079, 'zeliam.assessoria@defensoria.ms.gov.br', 'Zélia Miyuki Okagawa', '17');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(29, 29, 4079, 'monicam@defensoria.ms.gov.br', 'Mônica Maria de Salvo Fontoura', '18');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(30, 30, 4079, 'christianem@defensoria.ms.gov.br', 'Christiane Maria dos S. P. Jucá Interlando', '20');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(31, 31, 4079, 'marinak.assessoria@defensoria.ms.gov.br', 'Marina de Oliveira Krol Leite', '20');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(32, 32, 4079, 'pmattos@defensoria.ms.gov.br', 'Paulo Roberto Mattos', '21');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(33, 33, 4079, 'tathianyk.assessoria@defensoria.ms.gov.br', 'Tathiany Kleia da Silva Verone Parron', '21');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(34, 34, 4079, 'leslier@defensoria.ms.gov.br', 'Leslie dos Reis Gonçalves', '22');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(35, 35, 4079, 'tamarat.assessoria@defensoria.ms.gov.br', 'Tamara Thais Torraca Delgado', '22');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(36, 36, 4079, 'patriciae@defensoria.ms.gov.br', 'Patricia Elias Cozzolino de Oliveira', '23');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(37, 37, 4079, 'juliaf@defensoria.ms.gov.br', 'Julia Fumiko Hayashi Gonda', '25');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(38, 38, 4079, 'danielar.assessoria@defensoria.ms.gov.br', 'Daniela Ribeiro Charro Furtado', '25');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(39, 39, 4079, 'claudiab@defensoria.ms.gov.br', 'Claudia Bossay Assumpção Fassa', '26');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(40, 40, 4079, 'luizh.assessoria@defensoria.ms.gov.br', 'Luiz Henrique Raele Braga', '26');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(41, 41, 4079, 'janei@defensoria.ms.gov.br', 'Jane Ines Dietrich', '27');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(42, 42, 4079, 'adrianai.assessoria@defensoria.ms.gov.br', 'Adriana Iguma Fujii', '27');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(43, 43, 4079, 'pandre@defensoria.ms.gov.br', 'Paulo Andre Defante', '28');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(44, 44, 4079, 'ruiy.assessoria@defensoria.ms.gov.br', 'Rui Yamanishi Takei', '28');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(45, 45, 4079, 'renatag@defensoria.ms.gov.br', 'Renata Gomes Bernardes', '29');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(46, 46, 4079, 'vanessam.assessoria@defensoria.ms.gov.br', 'Vanessa Mara Marchioretto', '29');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(47, 47, 4079, 'aparecidom@defensoria.ms.gov.br', 'Aparecido Martinez Espinola', '31');
INSERT INTO dadosusuarios(`idDadosUsuario`, `idUsuario`, `idCidade`,`email`, `nomeCompleto`, `sala`)VALUES(48, 48, 4079, 'larissaf.assessoria@defensoria.ms.gov.br', 'Larissa França Giesen', '31');

